import { ReactComponent as Art } from '../assets/icons/art.svg';
import { ReactComponent as Book } from '../assets/icons/book.svg';
import { ReactComponent as Education } from '../assets/icons/education.svg';
import { ReactComponent as Climate } from '../assets/icons/climat.svg';
import { ReactComponent as Business } from '../assets/icons/business.svg';
import { ReactComponent as Automobiles } from '../assets/icons/automobiles.svg';

export const categoriesData = {
  "Admin": { icon: '' },
  "Arts": { icon: <Art /> },
  "Automobiles": { icon: <Automobiles /> },
  "Books": { icon: <Book /> },
  "Briefing": { icon: '' },
  "Business": { icon: <Business /> },
  "Climate": { icon: <Climate /> },
  "Corrections": { icon: '' },
  "Crosswords & Games": {},
  "Education": { icon: <Education /> },
  "En Español": {},
  "Fashion": {},
  "Food": {},
  "Guides": {},
  "Health": {},
  'Home & Garden': {},
  "Home Page": {},
  "Job Market": {},
  "Lens": {},
  "Magazine": {},
  "Movies": {},
  "Multimedia/Photos": {},
  "New York": {},
  "Obituaries": {},
  "Opinion": {},
  "Parenting": {},
  "Podcasts": {},
  "Reader Center": {},
  "Real Estate": {},
  "Science": {},
  "Smarter Living": {},
  "Sports": {},
  "Style": {},
  "Sunday Review": {},
  "T Brand": {},
  "T Magazine": {},
  "Technology": {},
  "The Learning Network": {},
  "The Upshot": {},
  "The Weekly": {},
  "Theater": {},
  "Times Insider": {},
  "Today’s Paper": {},
  "Travel": {},
  "U.S.Universal": {},
  "Video": {},
  "Well": {},
  "World": {},
  "Your Money": {},
};