export const ARTICLES_SECTIONS_FETCH = 'articles/ARTICLES_SECTIONS_FETCH';
export const ARTICLES_SECTIONS_RECEIVED = 'articles/ARTICLES_SECTIONS_RECEIVED';
export const ARTICLES_SECTIONS_CLEAR = 'articles/ARTICLES_SECTIONS_CLEAR';

export const ARTICLES_FETCH = 'articles/ARTICLES_FETCH';
export const ARTICLES_RECEIVED = 'articles/ARTICLES_RECEIVED';
export const ARTICLES_CLEAR = 'articles/ARTICLES_CLEAR';

export const TOP_STORIES_FETCH = 'articles/TOP_STORIES_FETCH';
export const TOP_STORIES_RECEIVED = 'articles/TOP_STORIES_RECEIVED';
export const TOP_STORIES_CLEAR = 'articles/TOP_STORIES_CLEAR';

export const MOST_POPULAR_FETCH = 'articles/MOST_POPULAR_FETCH';
export const MOST_POPULAR_RECEIVED = 'articles/MOST_POPULAR_RECEIVED';
export const MOST_POPULAR_CLEAR = 'articles/MOST_POPULAR_CLEAR';