export const ARTICLES_SECTIONS_FETCH = 'articles/ARTICLES_SECTIONS_FETCH';
export const ARTICLES_SECTIONS_RECEIVED = 'articles/ARTICLES_SECTIONS_RECEIVED';
export const ARTICLES_SECTIONS_CLEAR = 'articles/ARTICLES_SECTIONS_CLEAR';

export const ARTICLES_FETCH = 'articles/ARTICLES_FETCH';
export const ARTICLES_RECEIVED = 'articles/ARTICLES_RECEIVED';
export const ARTICLES_CLEAR = 'articles/ARTICLES_CLEAR';